# Release: https://github.com/zenopie/xmr-bridge/releases/tag/v0.0.3
# Workflow URL: https://github.com/zenopie/xmr-bridge/actions/runs/19753085333
# Commit: https://github.com/zenopie/xmr-bridge/commit/28bc13ffbc74277a7447d092d93db4de803a9be0
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/xmr-bridge@sha256:d4e4dbb521c67207ac76b5f5f1556daba68e705783640b16c6dd2dd8f364aecd
    ports:
      - '8000'
